[platformio]
default_envs = release
build_dir = ../compilacion/esp32

[env]
framework = arduino
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
platform_packages =
    platformio/framework-arduinoespressif32@https://github.com/espressif/arduino-esp32.git#3.1.1
    platformio/framework-arduinoespressif32-libs@https://dl.espressif.com/AE/esp-arduino-libs/esp32-3.1.1-h.zip
monitor_speed = 2000000
lib_deps =
    https://github.com/esp-arduino-libs/ESP32_Display_Panel.git#v1.0.4
    https://github.com/esp-arduino-libs/ESP32_IO_Expander.git#v1.1.0
    https://github.com/esp-arduino-libs/esp-lib-utils.git#v0.2.0
    https://github.com/lvgl/lvgl.git#v8.4.0
    bblanchon/ArduinoJson@^6.21.5
board_build.flash_size = 16MB
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions_clock.csv
build_unflags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
build_flags =
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_LVGL_H_INCLUDE_SIMPLE
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DARDUINO_USB_MODE=0
    -DBOARD_HAS_PSRAM
    -I src

[env:debug]
extends = env
board = BOARD_WAVESHARE_ESP32_S3_TOUCH_LCD_2_1
build_type = debug
build_flags =
    ${env.build_flags}
    -DCORE_DEBUG_LEVEL=3
    -DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
    -DBOARD_WAVESHARE_ESP32_S3_TOUCH_LCD_2_1
    -DLV_COLOR_16_SWAP=0

[env:release]
extends = env
board = BOARD_WAVESHARE_ESP32_S3_TOUCH_LCD_2_1
build_type = release
build_flags =
    ${env.build_flags}
    -DCORE_DEBUG_LEVEL=1
    -DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
    -DBOARD_WAVESHARE_ESP32_S3_TOUCH_LCD_2_1
    -DLV_COLOR_16_SWAP=0
